INSERT INTO EXPENSE(NAME, DESCRIPTION, DATE_REGISTER, AMOUNT) VALUES('Gabriel', 'Livro de Springboot', CURRENT_TIMESTAMP, 19.90);
INSERT INTO EXPENSE_TAGS(EXPENSE_ID, TAGS) VALUES('1', 'bom');
INSERT INTO EXPENSE_TAGS(EXPENSE_ID, TAGS) VALUES('1', 'ruim');
INSERT INTO EXPENSE_TAGS(EXPENSE_ID, TAGS) VALUES('1', 'legal');
INSERT INTO EXPENSE_TAGS(EXPENSE_ID, TAGS) VALUES('1', 'gostei');

INSERT INTO EXPENSE(NAME, DESCRIPTION, DATE_REGISTER, AMOUNT) VALUES('Veloso' , 'Livro de Hibernate' , CURRENT_TIMESTAMP, 39.90);
INSERT INTO EXPENSE_TAGS(EXPENSE_ID, TAGS) VALUES(2, 'ótimo');
INSERT INTO EXPENSE_TAGS(EXPENSE_ID, TAGS) VALUES(2, 'maravilha');
INSERT INTO EXPENSE_TAGS(EXPENSE_ID, TAGS) VALUES(2, 'perfeito');
INSERT INTO EXPENSE_TAGS(EXPENSE_ID, TAGS) VALUES(2, 'incrível');